### ISSUE TITLE
ldap_auth on elgg-2.3.2

### ISSUE THREAD

**Issue by nicaiseeric** [bruno-infotrad/ldap_auth#1]
Hi Bruno, I was trying to use this ldap_plugin on elgg-2.3.2. I'm facing  the following issue:

please any hint/help is welcome.

[php7:notice] [pid 758] [client x.x.x.x:p] Exception at time 1532980208: Error: Call to undefined function find_plugin_settings() in /var/www/elgg/mod/ldap_auth/start.php:44\nStack trace:\n#0 /var/www/elgg/vendor/elgg/elgg/engine/classes/ElggPAM.php(66): ldap_auth_authenticate(Array)\n#1 /var/www/elgg/vendor/elgg/elgg/engine/lib/sessions.php(139): ElggPAM->authenticate(Array)\n#2 /var/www/elgg/vendor/elgg/elgg/actions/login.php(39): elgg_authenticate('ldap_uid', 'ldap_uid')\n#3 /var/www/elgg/vendor/elgg/elgg/engine/classes/Elgg/Includer.php(18): include('/var/www/elgg/v...')\n#4 /var/www/elgg/vendor/elgg/elgg/engine/classes/Elgg/ActionsService.php(176): Elgg\\Includer::includeFile('/var/www/elgg/v...')\n#5 /var/www/elgg/vendor/elgg/elgg/engine/lib/actions.php(22): Elgg\\ActionsService->execute('login')\n#6 [internal function]: _elgg_action_handler(Array, 'action')\n#7 /var/www/elgg/vendor/elgg/elgg/engine/classes/Elgg/Router.php(100): call_user_func('_elgg_action_ha...', Array, 'action')\n#8 /var/www/elgg/vendor/elgg/elgg/engine/classes/Elgg/Application.php(436): Elgg\\Router->route(Object(Elgg\\Http\\Request))\n#9 /var/www/elgg/vendor/elgg/elgg/engine/classes/Elgg/Application.php(384): Elgg\\Application->run()\n#10 /var/www/elgg/index.php(8): Elgg\\Application::index()\n#11 {main}, referer: http://my.social.network.fr/

**Comment by bruno-infotrad** [comment]
Désolé, je n'ai pas mis ce plugin à jour depuis un bout de temps. La fonction find_plugin_settings n'existe plus. Je vais essayer de trouver le temps de mettre à jour pour la dernière version de Elgg.

**Comment by bruno-infotrad** [comment]
Vous pourriez essayer https://github.com/Elgg/ldap_auth, le code est dérivé du mien mais ils semblent l'avoir  mis à jour.

**Comment by nicaiseeric** [comment]
Ok merci pour le lien.
Je verrai ton code pour l.adapter (car j ai pas d expérience en php) et avoir une version du plugin pour elgg-2.3.2

**Comment by nicaiseeric** [comment]
J'ai essayé https://github.com/Elgg/ldap_auth. mais certaines functions (comme find_plugin_settings ) ont été supprimées dans les versions récentes de Elgg

**Comment by nicaiseeric** [comment]
En lisant un post ici https://elgg.org/plugins/384363/releases/1.8#elgg-object-1766268 
il y a une note : "Deprecated in 1.8: find_plugin_settings() is deprecated by elgg_get_calling_plugin_entity() or elgg_get_plugin_from_id()"

J'ai donc remplacé dans le start.php, line 44 , la function "find_plugin_settings" par "elgg_get_plugin_from_id"

Et ca marche comme un charme :)
